


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import Navbar from "./Navbar";
import { Theme } from "@radix-ui/themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen`}>
        <Theme className="md:flex h-screen">
          <div className="hidden md:block border-r">
            <Navbar/>
          </div>
          <main className="flex flex-col flex-grow ">
            <div className="md:hidden">
              <Navbar/>
            </div>
              {children}
          </main>
        </Theme>
      </body>
    </html>
  );
}
