


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import Navbar from "./Navbar";
import { Theme } from "@radix-ui/themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Theme>
          <div className="flex h-screen">
            {/* Sidebar - Only visible on md+ */}
            <div className="hidden md:block bg-orange-300">
              <Navbar />
            </div>

            {/* Main Content Area */}
            <main className="flex-1 bg-purple-500">
              
              {/* Top Navbar - Visible only on small screens */}
              <div className="md:hidden">
                <Navbar />
              </div>
              <div className="p-4">
                {children}
              </div>
            </main>
          </div>
        </Theme>
      </body>
    </html>
  );
}
